typography_spectrum: 0.8768070536345649
color:
  brandStrength: 0.8674235630051076
  lightness: 0.6022752681230702
  saturation: 0.40708123940356666
  rhythmicContrast: 0.06681689764732623
  brandColors:
    - '#FF5335'
    - '#B39C85'
    - '#306E73'
    - '#3B424D'
    - '#1D181F'
github: true
layout_spectrum: 0.5723398582344081
analytics:
  google: UA-86820651-1
author:
  name: 'Natalie Dixon '
  email: nataliedixonlive@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/50c6d388-7289-4cb5-bbad-50aee8746e48.png
name: Raven Training Solutions
url: 'http://www.raventrainingsolutions.co.uk'
navigation:
  - name: Training Solutions
    id: ccb7e81a-b507-48f0-b611-88bcfec0262f
    type: content
  - name: Services
    id: 6b27b78d-6860-47e0-8743-774490d2e6bd
    type: content
  - name: Courses
    id: 784f63c1-80d6-4ed8-a179-622f02f1cb87
    type: content
  - name: Request A Call Back
    id: ea47221b-c0c7-41c3-8e38-8c7f5f9a7710
    type: content
  - name: Testimonials
    id: 41dfa7f8-883f-421f-938d-9cfe355c7218
    type: content
  - name: Blog / Case Studies
    id: 9ad9555e-3aaf-42a0-be8f-e53ccb8e5586
    type: content
  - name: About Us
    id: 8fe162e4-c419-419c-9b05-601e8f0d65cb
    type: content
favicon: null
title: Construction Training | Management | CITB Grant Recovery
content: []
description: RAVEN TRAINING SOLUTIONS
purpose:
  - type: contact
    url: 'tel:02032869866'
    label: Call 0203 2869866
  - type: contact
    url: 'mailto:admin@raventrainingsolutions.co.uk'
    label: Email
