layout_spectrum: 0.03662461657648777
typography_spectrum: 0.5492773240331634
color:
  brandStrength: 0.18600175825085968
  lightness: 0.2951498357805949
  saturation: 0.969602740215654
  rhythmicContrast: 0.9080868696498842
  brandColors:
    - '#FF5335'
    - '#B39C85'
    - '#306E73'
    - '#3B424D'
    - '#1D181F'
github: true
analytics:
  google: UA-86820651-1
author:
  name: 'Natalie Dixon '
  email: nataliedixonlive@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/50c6d388-7289-4cb5-bbad-50aee8746e48.png
name: Raven Training Solutions
url: 'http://raventrainingsolutions.co.uk/'
navigation:
  - name: Training Solutions
    id: ccb7e81a-b507-48f0-b611-88bcfec0262f
    type: content
  - name: Services
    id: 6b27b78d-6860-47e0-8743-774490d2e6bd
    type: content
  - name: Courses
    id: 784f63c1-80d6-4ed8-a179-622f02f1cb87
    type: content
  - name: Request A Call Back
    id: ea47221b-c0c7-41c3-8e38-8c7f5f9a7710
    type: content
  - name: Testimonials
    id: 41dfa7f8-883f-421f-938d-9cfe355c7218
    type: content
  - name: Blog / Case Studies
    id: 9ad9555e-3aaf-42a0-be8f-e53ccb8e5586
    type: content
  - name: About Us
    id: 8fe162e4-c419-419c-9b05-601e8f0d65cb
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6eebed97-b497-4fb6-851c-28aa3b069a43.png
title: Construction Training | Management | CITB Grant Recovery
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FkT6tdum4tt0%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DkT6tdum4tt0&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FkT6tdum4tt0%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Natalie Dixon
          url: 'https://www.youtube.com/channel/UCe_I-JgF2NnNDa4lZElTkAQ'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - toy
        - dixon
        - baby
        - natalie
        - freaks
        - duration
        - crybaby
        - annabelle
        - kinder
        - sundae
      description: Uploaded by Natalie Dixon on 2017-02-03.
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=kT6tdum4tt0&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=kT6tdum4tt0&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=kT6tdum4tt0&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=kT6tdum4tt0&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=kT6tdum4tt0&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=kT6tdum4tt0'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=kT6tdum4tt0
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=kT6tdum4tt0
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/kT6tdum4tt0'
      title: CITB Grant Recovery and construction training
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: RAVEN TRAINING SOLUTIONS
purpose:
  - type: contact
    url: 'tel:02032869866'
    label: Call 0203 2869866
  - type: contact
    url: 'mailto:admin@raventrainingsolutions.co.uk'
    label: Email
content_rating:
  adult: false
